"""
models/insights.py — Semantic insight, recommendation, and cost-impact models.

These are the core output types returned by all specialized agents.
All monetary values are in INR.

Validates:
  - Property 4:  Insights include business context, severity, and recommendations
  - Property 14: CostImpact includes monthly and annual INR projections
  - Property 23: Recommendations include action, rationale, steps, expected_benefit
"""

from __future__ import annotations

import enum
from typing import Annotated

from pydantic import BaseModel, Field, model_validator


class Urgency(str, enum.Enum):
    """Urgency level for insights — determines alert priority and display colour."""

    IMMEDIATE = "immediate"  # P0 — page someone now
    HIGH = "high"            # P1 — fix today
    MEDIUM = "medium"        # P2 — fix this sprint
    LOW = "low"              # P3 — backlog


class InsightCategory(str, enum.Enum):
    """Broad category of the insight for routing and filtering."""

    ANOMALY = "anomaly"
    PERFORMANCE = "performance"
    COST = "cost"
    SECURITY = "security"
    CONFIGURATION = "configuration"
    CAPACITY = "capacity"
    CICD = "cicd"
    DATABASE = "database"


class ImplementationEffort(str, enum.Enum):
    """Rough estimate of effort to implement a recommendation."""

    LOW = "low"       # < 1 hour
    MEDIUM = "medium" # 1–8 hours
    HIGH = "high"     # > 1 day


class CostImpact(BaseModel):
    """
    Projected cost impact of an infrastructure change or recommendation.

    All values are in INR. The annual_inr validator enforces that
    annual ≈ monthly × 12 (within 1% tolerance) to catch data entry errors.

    Validates Property 14.
    """

    monthly_inr: float = Field(ge=0.0, description="Monthly cost impact in INR (positive = saving)")
    annual_inr: float = Field(ge=0.0, description="Annual cost impact in INR")
    confidence: Annotated[float, Field(ge=0.0, le=1.0)] = Field(
        description="Confidence in the estimate (0–1)"
    )
    description: str = Field(min_length=1, description="Human-readable summary of the cost impact")
    breakdown: dict[str, float] = Field(
        default_factory=dict,
        description="Per-resource breakdown of the cost impact in INR",
    )

    @model_validator(mode="after")
    def validate_annual_approx_monthly_times_12(self) -> "CostImpact":
        """annual_inr must be within 1% of monthly_inr × 12."""
        if self.monthly_inr == 0:
            return self
        expected = self.monthly_inr * 12
        tolerance = expected * 0.01  # 1%
        if abs(self.annual_inr - expected) > tolerance:
            raise ValueError(
                f"annual_inr ({self.annual_inr:.2f}) must equal monthly_inr × 12 "
                f"({expected:.2f}) within 1% tolerance"
            )
        return self


class Recommendation(BaseModel):
    """
    An actionable recommendation produced by a specialized agent.

    All four required fields (action, rationale, steps, expected_benefit)
    must be non-empty to satisfy Property 23.
    """

    action: str = Field(min_length=1, description="Short imperative description of the action")
    rationale: str = Field(min_length=1, description="Why this action is recommended")
    steps: list[str] = Field(min_length=1, description="Ordered implementation steps")
    expected_benefit: str = Field(
        min_length=1,
        description="Concrete outcome after implementation (e.g. '40% latency reduction')",
    )
    cost_impact: CostImpact | None = None
    effort: ImplementationEffort = ImplementationEffort.MEDIUM
    priority: int = Field(
        default=50,
        ge=1,
        le=100,
        description="Priority score 1–100; higher = more important. Used for ranking.",
    )
    related_commit_sha: str | None = Field(
        default=None,
        description="Commit SHA that introduced the problem, if attributable",
    )
    sql_ddl: str | None = Field(
        default=None,
        description="SQL DDL statement (e.g. CREATE INDEX) if applicable",
    )


class Insight(BaseModel):
    """
    A semantic insight generated by a specialized agent.

    Transforms raw metric/config data into human-readable findings with
    business context. Validates Property 4.
    """

    category: InsightCategory
    component: str = Field(min_length=1, description="Infrastructure component (e.g. celery-worker, rds-postgres)")
    title: str = Field(min_length=1, description="One-line summary")
    business_context: str = Field(
        min_length=1,
        description="Business impact in plain English, e.g. 'Users are experiencing 3x slower checkouts'",
    )
    urgency: Urgency = Urgency.MEDIUM
    confidence: Annotated[float, Field(ge=0.0, le=1.0)] = Field(
        description="Model confidence in this insight (0–1)"
    )
    recommendations: list[Recommendation] = Field(
        default_factory=list,
        description="One or more actionable recommendations",
    )
    supporting_data: dict[str, object] = Field(
        default_factory=dict,
        description="Raw data that supports this insight (metric samples, log lines, etc.)",
    )
    attribution: str | None = Field(
        default=None,
        description="Commit SHA, config file, or timestamp that caused this issue (Property 31)",
    )
